### ISSUE TITLE
KeyError: 'video.mp4'

### ISSUE THREAD

**Issue by 123454xiao** [kocurvik/aicc#3]
When I run the single mp4, There is the issum:
 (aicc) xiaoyuting@kemove-X10DRi:/data/xiao/aicc-master$ python run_single_video_                threaded.py /path/to/video.mp4
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/xiaoyuting/.conda/envs/aicc/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/xiaoyuting/.conda/envs/aicc/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "run_single_video_threaded.py", line 31, in video_reader_thread_fn
    video_id, camera_id, max_frames, width, height = get_video_params(path)
  File "/data/xiao/aicc-master/res/video_params.py", line 26, in get_video_params
    d = VIDEO_PARAM_DICT[filename]
KeyError: 'video.mp4'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/xiaoyuting/.conda/envs/aicc/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/xiaoyuting/.conda/envs/aicc/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "run_single_video_threaded.py", line 48, in model_thread_fn
    video_id, camera_id, max_frames, width, height = get_video_params(path)
  File "/data/xiao/aicc-master/res/video_params.py", line 26, in get_video_params
    d = VIDEO_PARAM_DICT[filename]
KeyError: 'video.mp4'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/xiaoyuting/.conda/envs/aicc/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/xiaoyuting/.conda/envs/aicc/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "run_single_video_threaded.py", line 75, in tracker_thread_fn
    video_id, camera_id, max_frames, width, height = get_video_params(path)
  File "/data/xiao/aicc-master/res/video_params.py", line 26, in get_video_params
    d = VIDEO_PARAM_DICT[filename]
KeyError: 'video.mp4'

Does anybody have the same issum?

**Comment by kocurvik** [comment]
In the command:
`python run_single_video_threaded.py /path/to/video.mp4`

You have to replace the `/path/to/video.mp4` with the actual path to the mp4 file.

Note that it has to be one of the AIC 2021 Track 1 videos for the proper annotations for classification into different movements of interest to be found.
